name: Deploy Backend to AKS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


name: Deploy Backend to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build & Push Docker Image
      run: |
        docker build -t ghcr.io/cnicole03-bit/admu-backend:latest .
        docker push ghcr.io/cnicole03-bit/admu-backend:latest

    - name: Deploy to AKS
      run: |
        kubectl apply -f backend-deployment.yaml
        kubectl rollout restart deployment logistics-backend
